name: Delete S3 Bucket

on:
  workflow_dispatch: # Permite disparar manualmente o workflow

jobs:
  delete-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://tf-state-bucket-eks --recursive

      - name: Delete S3 Bucket
        run: |
          aws s3api delete-bucket --bucket tf-state-bucket-eks --region us-east-1