name: Orchestrate Terraform Workflows

on:
  workflow_dispatch:

jobs:
  rds:
    name: Trigger RDS Workflow
    runs-on: ubuntu-latest    
    steps:
      - name: Trigger RDS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'database-terraform',
              workflow_id: 'workflows/deploy.yml', # Nome do workflow no repositório de rds
              ref: 'main'
            })
          debug: true

  eks:
    name: Trigger EKS Workflow
    runs-on: ubuntu-latest
    needs: rds 
    steps:
      - name: Trigger EKS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'workflows/eks-repo',
              workflow_id: 'provisioning-cluster-eks-fargate.yml', # Nome do workflow no repositório de eks
              ref: 'main'
            })
          debug: true
