name: Orchestrate Terraform Workflows

on:
  workflow_dispatch:

jobs:
  rds:
    name: Trigger RDS Workflow
    runs-on: ubuntu-latest    
    steps:
      - name: Trigger RDS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'database-terraform',
              workflow_id: 'deploy.yml',
              ref: 'main'
            });

  eks:
    name: Trigger EKS Workflow
    runs-on: ubuntu-latest
    needs: rds 
    steps:
      - name: Trigger EKS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'workflows/eks-repo',
              workflow_id: 'provisioning-cluster-eks-fargate.yml',
              ref: 'main'
            });
