name: Orchestrate Terraform Workflows

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  network:
    name: Trigger network Workflow
    runs-on: ubuntu-latest   
    steps:
      - name: Trigger network Terraform Apply
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'infra',
              workflow_id: 'deploy.yaml',
              ref: 'main'
              headers: {
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`
              }
            });
  rds:
    name: Trigger RDS Workflow
    runs-on: ubuntu-latest
    needs: network  
    steps:
      - name: Trigger RDS Terraform Apply
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'database-terraform',
              workflow_id: 'deploy.yaml',
              ref: 'main'
              headers: {
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`
              }
            });

  eks:
    name: Trigger EKS Workflow
    runs-on: ubuntu-latest
    needs: rds
    steps:
      - name: Trigger EKS Terraform Apply
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'eks-repo',
              workflow_id: 'provisioning-cluster-eks-fargate.yml',
              ref: 'main'
              headers: {
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`
              }
            });
