name: Orchestrate Terraform Workflows

on:
  workflow_dispatch:

jobs:
  # network:
  #   name: Trigger Infra Workflow
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Network Terraform Apply
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           github.rest.actions.createWorkflowDispatch({
  #             owner: 'pedidos-techallenge',
  #             repo: 'infra',
  #             workflow_id: 'deploy.yml', # Nome do workflow no repositório de network
  #             ref: 'main'
  #           })
  rds:
    name: Trigger RDS Workflow
    runs-on: ubuntu-latest
    #needs: network # Garante que este job só será executado após o job network
    steps:
      - name: Trigger RDS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'database-terraform',
              workflow_id: 'deploy.yml', # Nome do workflow no repositório de rds
              ref: 'main'
            })

  eks:
    name: Trigger EKS Workflow
    runs-on: ubuntu-latest
    needs: rds # Garante que este job só será executado após o job rds
    steps:
      - name: Trigger EKS Terraform Apply
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'pedidos-techallenge',
              repo: 'eks-repo',
              workflow_id: 'provisioning-cluster-eks-fargate.yml', # Nome do workflow no repositório de eks
              ref: 'main'
            })
