name: Provisioning Cluster EKS With Fargate

on: 
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket --bucket tf-state-bucket-eks --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
          aws s3api put-bucket-encryption --bucket tf-state-bucket-eks --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
          aws s3api put-bucket-policy --bucket tf-state-bucket-eks --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::117590171476:role/LabRole"
                },
                "Action": "s3:*",
                "Resource": [
                  "arn:aws:s3:::tf-state-bucket-eks",
                  "arn:aws:s3:::tf-state-bucket-eks/*"
                ]
              }
            ]
          }'
          aws s3api put-public-access-block --bucket tf-state-bucket-eks --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

  terraform:
    runs-on: ubuntu-latest
    needs: create-s3-bucket # Garante que este job só será executado após o job network
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v1 
      
      # Provisioning the EKS with fargate
      - name: terraform-init
        run: terraform -chdir=./eks init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=eks.tfstate" -backend-config="region=us-east-1"      

      - name: terraform-apply
        run: terraform -chdir=./eks apply -auto-approve